
import java.awt.Color;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author prabath
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        incorrectlbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        incorrectlbl = new javax.swing.JLabel();
        usernamelbl = new javax.swing.JTextField();
        passwordlbl = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        showpasswordcb = new javax.swing.JCheckBox();
        closebtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(768, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel1.setText("LOGIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, 70));

        incorrectlbl.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        incorrectlbl.setForeground(new java.awt.Color(255, 0, 51));
        incorrectlbl.setIcon(new javax.swing.ImageIcon("/media/prabath/New Volume/works/NetBeansProjects/gym_management_system/src/main/java/pictures/close.png")); // NOI18N
        incorrectlbl.setText("Incorrect Username or Password");
        jPanel1.add(incorrectlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, 30));

        usernamelbl.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        usernamelbl.setText("Enter Username");
        usernamelbl.setName("username"); // NOI18N
        usernamelbl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernamelblFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernamelblFocusLost(evt);
            }
        });
        usernamelbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamelblActionPerformed(evt);
            }
        });
        jPanel1.add(usernamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 276, 30));

        passwordlbl.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        passwordlbl.setText("Enter Password");
        passwordlbl.setToolTipText("Password");
        passwordlbl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordlblFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordlblFocusLost(evt);
            }
        });
        jPanel1.add(passwordlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 276, 30));

        jButton2.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("/media/prabath/New Volume/works/NetBeansProjects/gym_management_system/src/main/java/pictures/login.png")); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, 40));

        showpasswordcb.setText("Show Password");
        showpasswordcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordcbActionPerformed(evt);
            }
        });
        jPanel1.add(showpasswordcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, 30));

        closebtn.setIcon(new javax.swing.ImageIcon("/media/prabath/New Volume/works/NetBeansProjects/gym_management_system/src/main/java/pictures/close.png")); // NOI18N
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        jPanel1.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("/media/prabath/New Volume/works/NetBeansProjects/gym_management_system/src/main/java/pictures/login background.PNG")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, 0, 1150, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to exit?","Select",JOptionPane.YES_NO_OPTION);
        if(a == 0){
            System.exit(a);
        }
    }//GEN-LAST:event_closebtnActionPerformed

    private void showpasswordcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordcbActionPerformed
        // TODO add your handling code here:
        if (showpasswordcb.isSelected()) {
            passwordlbl.setEchoChar((char)0);
        }else{
            passwordlbl.setEchoChar('*');
        }
        
    }//GEN-LAST:event_showpasswordcbActionPerformed

    private void passwordlblFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordlblFocusLost
        // TODO add your handling code here:
        incorrectlbl.setVisible(false);
        if (passwordlbl.getText().equals("")) {
            passwordlbl.setText("Enter Password");
            passwordlbl.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_passwordlblFocusLost

    private void passwordlblFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordlblFocusGained
        // TODO add your handling code here:
        incorrectlbl.setVisible(false);
        if (passwordlbl.getText().equals("Enter Password")) {
            passwordlbl.setText("");
            passwordlbl.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_passwordlblFocusGained

    private void usernamelblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamelblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamelblActionPerformed

    private void usernamelblFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernamelblFocusLost
        // TODO add your handling code here:
        incorrectlbl.setVisible(false);
        if (usernamelbl.getText().equals("")) {
            usernamelbl.setText("Enter Username");
            usernamelbl.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_usernamelblFocusLost

    private void usernamelblFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernamelblFocusGained
        // TODO add your handling code here:
        incorrectlbl.setVisible(false);
        if (usernamelbl.getText().equals("Enter Username")) {
            usernamelbl.setText("");
            usernamelbl.setForeground(new Color(0,118,221));
        }
    }//GEN-LAST:event_usernamelblFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (usernamelbl.getText().equals("gms") && passwordlbl.getText().equals("123")) {
            setVisible(false);
            new home().setVisible(true);
        }else{
            incorrectlbl.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JLabel incorrectlbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordlbl;
    private javax.swing.JCheckBox showpasswordcb;
    private javax.swing.JTextField usernamelbl;
    // End of variables declaration//GEN-END:variables
}
